version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      # a packaged system that has the instructions for creating a running container.
      - image: circleci/ruby:2.3.3

    # actions that need to be taken to perform your job
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:USaw9IC3qDmo5lTDeDE1ctu2VeLlrFbqhYZrPVJlw2U"
            - "c0:90:93:c0:d1:79:9e:d6:14:2e:0f:30:77:1a:83:04"

      - restore_cache:
          keys:
            - source-v1- #one time, not every time!

      # checks out the source code for a job over SSH
      - checkout

      - save_cache:
          key: source-v1-1 # Sept 7, 2019
          paths:
            - ".git"

      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1

      - run:
          name: install dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: deployment
          command: |
            git config --global user.email "accounts@plot.ly"
            git config --global user.name "Deployer"
            rm -rf _posts/python/html
            git clone -b built git@github.com:plotly/plotly.py-docs _posts/python/html
            bundle exec jekyll build
            mkdir snapshots && mkdir snapshots/python && mkdir snapshots/python/v3 && mkdir snapshots/r && mkdir snapshots/javascript && mkdir snapshots/ggplot2 && mkdir snapshots/matplotlib && mkdir snapshots/matlab && mkdir snapshots/python/getting-started && mkdir snapshots/python/plotly-fundamentals && mkdir snapshots/python/line-and-scatter && mkdir snapshots/r/getting-started && mkdir snapshots/r/plotly-fundamentals && mkdir snapshots/r/line-and-scatter && mkdir snapshots/javascript/getting-started && mkdir snapshots/javascript/plotly-fundamentals && mkdir snapshots/javascript/line-and-scatter && mkdir snapshots/ggplot2/getting-started && mkdir snapshots/ggplot2/geom_abline && mkdir snapshots/matplotlib/getting-started && mkdir snapshots/matplotlib/plot && mkdir snapshots/python/v3/getting-started && mkdir snapshots/python/v3/line-and-scatter && mkdir snapshots/python/v3/plotly-fundamentals && mkdir snapshots/matlab/getting-started && mkdir snapshots/matlab/graphing-multiple-chart-types && mkdir snapshots/matlab/scatter
            cd _site
            echo `pwd`
            cp -r all_static ../snapshots
            cp index.html ../snapshots
            cp python/index.html ../snapshots/python
            cp python/getting-started/index.html ../snapshots/python/getting-started
            cp python/plotly-fundamentals/index.html ../snapshots/python/plotly-fundamentals
            cp python/line-and-scatter/index.html ../snapshots/python/line-and-scatter
            cp r/index.html ../snapshots/r
            cp r/getting-started/index.html ../snapshots/r/getting-started
            cp r/plotly-fundamentals/index.html ../snapshots/r/plotly-fundamentals
            cp r/line-and-scatter/index.html ../snapshots/r/line-and-scatter
            cp javascript/index.html ../snapshots/javascript
            cp javascript/plotly-fundamentals/index.html ../snapshots/javascript/plotly-fundamentals
            cp javascript/getting-started/index.html ../snapshots/javascript/getting-started
            cp javascript/line-and-scatter/index.html ../snapshots/javascript/line-and-scatter
            cp ggplot2/index.html ../snapshots/ggplot2
            cp ggplot2/getting-started/index.html ../snapshots/ggplot2/getting-started
            cp ggplot2/geom_abline/index.html ../snapshots/ggplot2/geom_abline
            cp matplotlib/index.html ../snapshots/matplotlib
            cp matplotlib/getting-started/index.html ../snapshots/matplotlib/getting-started
            cp matplotlib/plot/index.html ../snapshots/matplotlib/plot
            cp python/v3/index.html ../snapshots/python/v3
            cp python/v3/plotly-fundamentals/index.html ../snapshots/python/v3/plotly-fundamentals
            cp python/v3/getting-started/index.html ../snapshots/python/v3/getting-started
            cp python/v3/line-and-scatter/index.html ../snapshots/python/v3/line-and-scatter
            cp matlab/index.html ../snapshots/matlab
            cp matlab/getting-started/index.html ../snapshots/matlab/getting-started
            cp matlab/graphing-multiple-chart-types/index.html ../snapshots/matlab/graphing-multiple-chart-types
            cp matlab/scatter/index.html ../snapshots/matlab/scatter
            percy snapshot snapshots --enable_javascript
            cd ..
            if [ "${CIRCLE_BRANCH}" == "source-design-merge" ]; then
             git checkout gh-pages 
             git pull origin gh-pages 
             cp -r _site/* . 
             rm -rf _site/ 
             touch .nojekyll 
             git add .
             git commit -m \"#{message}\" 
             git push origin gh-pages
            fi
